//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESERVATION_SYSTEM.Domain.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public MessagesExceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RESERVATION_SYSTEM.Domain.Exceptions.MessagesExceptions", typeof(MessagesExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the customer name  is already created.
        /// </summary>
        public static string NameCustomerNotValid {
            get {
                return ResourceManager.GetString("NameCustomerNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the service name  is already created.
        /// </summary>
        public static string NameServiceNotValid {
            get {
                return ResourceManager.GetString("NameServiceNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date must be greater than the start date..
        /// </summary>
        public static string ValidateEndDateIsAfterStartDateFailed {
            get {
                return ResourceManager.GetString("ValidateEndDateIsAfterStartDateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the time of the reservation is not in the allowed range for the place..
        /// </summary>
        public static string ValidateReservationTimeLimitFailed {
            get {
                return ResourceManager.GetString("ValidateReservationTimeLimitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the user already has another reservation in this time range..
        /// </summary>
        public static string ValidateReservationUserSpaceAvailabilityInDateRangeByCreate {
            get {
                return ResourceManager.GetString("ValidateReservationUserSpaceAvailabilityInDateRangeByCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected space is already reserved for the given dates..
        /// </summary>
        public static string ValidateSpaceAvailabilityInDateRangeByCreateFailed {
            get {
                return ResourceManager.GetString("ValidateSpaceAvailabilityInDateRangeByCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the number of people to enter exceeds the capacity of the space..
        /// </summary>
        public static string ValidateSpaceCapacityFailed {
            get {
                return ResourceManager.GetString("ValidateSpaceCapacityFailed", resourceCulture);
            }
        }
    }
}
